### ISSUE TITLE
jquery-no-globalEvalのruleの実装が間違っている

### ISSUE THREAD

**Issue by kyasbal** [mrtc0/eslint-plugin-domxss#1]
https://github.com/mrtc0/eslint-plugin-domxss/blob/master/lib/rules/jquery-no-globalEval.js

`$.add`の実装のコピーのままになっています。

**Comment by mrtc0** [comment]
https://github.com/mrtc0/eslint-plugin-domxss/commit/99a8a9dd180f724f46be9e42e3a21533cd7c167b
